### ISSUE TITLE
Create a Golang struct for collection objects

### ISSUE THREAD

**Issue by straup** [aaronland/go-smithsonian-openaccess#2]
I guess first it needs to be determined whether they are all the same...

**Comment by thisisaaronland** [comment]
* https://edan.si.edu/openaccess/docs/more.html
* https://sirismm.si.edu/siris/EDAN_IMM_OBJECT_RECORDS_1.09.pdf

**Comment by thisisaaronland** [comment]
"The primary content in the repository at this time is collection data which we type as edanmdm."
