### ISSUE TITLE
Read list of units from metadata/edan/index.txt

### ISSUE THREAD

**Issue by straup** [aaronland/go-smithsonian-openaccess#7]
As in update these:

* https://github.com/aaronland/go-smithsonian-openaccess/blob/master/walk/walk.go#L128
* https://github.com/aaronland/go-smithsonian-openaccess/blob/master/smithsonian.go

To pull from this:

https://smithsonian-open-access.s3-us-west-2.amazonaws.com/metadata/edan/index.txt

**Comment by thisisaaronland** [comment]
No longer an issue
